# Intrinics for the rgbd camera used in visual odometry
# X position of the optical center
cx: 319.5

# Y position of the optical center
cy: 239.5

# Focal length in X direction
fx: 570.1754150390625

# Focal length in Y direction
fy: 570.1754150390625

# Camera Name
camera_name: astra

# RGBD Depth image topic
depth_topic: /summit_xl/front_rgbd_camera/depth_registered/image_raw

#RGBD rgb image topic
rgb_topic: /summit_xl/front_rgbd_camera/rgb/image_raw
