# Intrinics for the rgbd camera used in visual odometry
# X position of the optical center
cx: 319.5

# Y position of the optical center
cy: 239.5

# Focal length in X direction
fx: 525.0

# Focal length in Y direction
fy: 525.0

# Camera name
camera_name: kinect

# RGBD Depth image topic
depth_topic: /camera/depth/image

#RGBD rgb image topic
rgb_topic: /camera/rgb/image_color
